### ISSUE TITLE
Wording problem for the "swipe to mark" items preference option.

### ISSUE THREAD

**Issue by wjjessen** [aminecmi/ReaderforSelfoss#147]
The option "Mark articles as read when scrolling..." is not working. I expect that articles will be marked as read when I scroll past them but they're not. 

App version: 156201712070626-store 
Selfoss version: 2.18-feef0a5 
Device: LG G5
OS: Android 6.0.1

**Comment by aminecmi** [comment]
Hi,

I think I misworded the option. This one should mark them as read when you **swipe** between them in the viewpager (article viewer). I will fix this.

Would you find the "scroll to mark" feature useful ?

**Comment by wjjessen** [comment]
If by "scroll to mark" you mean scroll past read items to the first unread item, it seems unnecessary if the Selfoss defaults.ini file is configured with "auto_hide_read_on_mobile=1". That setting hides read items in Reader for Selfoss.

**Comment by aminecmi** [comment]
@wjjessen The setting on the website has no relation with the app. 
The setting I added mark them as read when you swipe left and right in the article viewer (after clicking an article)
I could add another setting that would mark items as read that would work as the "auto_hide_read_on_mobile" setting for the web version.
