### ISSUE TITLE
feature: support gif animation

### ISSUE THREAD

**Issue by eephyne** [aminecmi/ReaderforSelfoss#149]
### Description

It would be nice to have gif animation on article instead of having to open the webpage
I can provide more information if needed but right now I can't really see what to add :p.

thanks for your work

**Comment by aminecmi** [comment]
Hi @eephyne,

Thanks for the request. Do you have some rss sources that have gifs inside. I would like to test this before to see if it's easy or not.

**Comment by eephyne** [comment]
of course.

http://lesjoiesducode.tumblr.com/rss for exemple

**Comment by aminecmi** [comment]
@eephyne What type of spout do you use for this source on the web instance of Selfoss ?

**Comment by eephyne** [comment]
If by spout you mean the type of RSS is leave it standard so RSS Feed

**Comment by aminecmi** [comment]
Thanks, I'll look into this.

**Comment by aminecmi** [comment]
@eephyne, Displaying the image inside the article in the article viewer will be a little hard.

I'll do it, but not right now.

**Comment by aminecmi** [comment]
@eephyne The feature is enabled. If you want to use it, you'll have to enable the `Use a webview in the article viewer.` setting in the app.

The loading may be a little slower, but gifs will be displayed.

**Comment by eephyne** [comment]
I downloaded the latest apk but I don't find the option, either I'm blind or the build isn't up to date.
You have a funny way of "I'll do it, but not right now", you're pretty fast :)

**Comment by aminecmi** [comment]
@eephyne It's still in alpha on the play store. I'll use the  app for a couple of days, and if everything works as intended, I'll move the apk to production (You can download manually the alpha apk from [here](https://jenkins.amine-bou.fr/job/ReaderForSelfoss/lastSuccessfulBuild/artifact/SignApksBuilder-out/selfoss-key/selfoss/app-githubConfig-release-unsigned.apk/app-githubConfig-release.apk))

Well, I didn't do it two days ago :) I was just testing some solutions and the last one worked quite well, so I went with it.

**Comment by eephyne** [comment]
huhu, using your link, the app crash on startup

**Comment by aminecmi** [comment]
On it. I'll update this comment with the fixed apk when it's done.

**Comment by aminecmi** [comment]
@eephyne the issue is solved. You can use the same link to download the apk.

**Comment by eephyne** [comment]
works great ! thanks
Juste one thing, the webview background does'nt follow the theme. work on light but still light bg on dark theme.
I also had one issue but cannot reproduce. When loading the gif rss of already seen items the first time, it stopped showing the gif after five or six swipe (even the first ones did'nt show up anymore).
It seem to also have solved another issue I had with low resolution image on some article (or its maybe another thing that you did between the stable and this one
anyway, thanks a lot, you're great :).

**Comment by aminecmi** [comment]
@eephyne glad it works :)

Could you open another issue for the background theme colors please ?

And if the other bugs happen again, could you open issues for each one ?

Thanks
