### ISSUE TITLE
Source icon from text issue.

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#155]
[This line](https://github.com/aminecmi/ReaderforSelfoss/blob/master/app/src/main/java/apps/amine/bou/readerforselfoss/utils/ItemsUtils.kt#L11) may cause a "StringIndexOutOfBound exception".

**Comment by Mashinist555** [comment]
Hi!
May I fix this issue? If yes, please assign me to the task.

**Comment by aminecmi** [comment]
Hi @Mashinist555,

I can't assign it to you. It's maybe because you need to be a contributor.
Still, I added the status "Taken" so you can take it, and make a pull request whenever you want.

**Comment by aminecmi** [comment]
Thanks @Mashinist555. This is now closed.
