### ISSUE TITLE
Article list automatically scrolls to top when exiting an article

### ISSUE THREAD

**Issue by aancel** [aminecmi/ReaderforSelfoss#169]
### Prerequisites

* [x] Are you running the latest version? 157201801020634-store
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

When exiting an article, the article list sometimes scrolls to the top of the list. It seems to happen when new articles are available and fetched.
I don't think that any option I've set might be the cause of it. It could be an idea to add an option to stay where you were in the article list, even when new articles are fetched.

### Steps to Reproduce

1. Open an article in the article list while being below the top of the article list (in term of scrolling)
2. Return to the article list

**Expected behavior:** Stay at the same position in the article list as previously.

**Actual behavior:** The application sometimes scrolls to the top of the list, forcing the user to go back to where he/she was before.

### Device

- Device : LG V20
- OS : Android Stock 7.0
- App version : 157201801020634-store

**Comment by aminecmi** [comment]
Hi,

This is indeed the current behavior. It was done like this so that the content would be refreshed when resuming the app after it was sent to the background (switching apps for example). The behavior is the same when going back to the list from the article viewer.

- Should the articles be loaded AND the view stay at the right (old) article ? (This could be tricky)

-  Should this be handled like Facebook (I don't have other example), stay at the same position and have some "new items available" button appear that scroll to the top and load the new ones ?

- Should the same behavior happen when switching the app, and returning from the article viewer ?

**Comment by aancel** [comment]
OK, I'm glad to hear that this is an existing behavior, and not a device specific issue ! 

Regarding to your questions:
- Indeed this would be the behavior that I would like ! I see why it would be tricky.

- Yes, this could be implemented this way. I think that scrolling to the top could also be implemented by clicking on the "Reader for Selfoss" text at the top, don't you think ? Anyone could benefit from this too

- I think it would be safe to assume that switching back to the app can result in refreshing the list and going to the top, as there is a context change between apps here.

My point here is just about the reading flow, that differs for each person. Some will prefer the way in is now, other might only use the article viewer.
I personnally like to browse the article list, when I find an interesting one I read it, and then go back to the list continuing with the next articles. If I remember well feedly has this behavior.

Anyway, thanks a lot for taking this into consideration, and thanks for this great RSS app !

P.S. Sorry for the potential typos, this was written on a phone !

**Comment by aminecmi** [comment]
Hi,

Right now on the alpha channel, there is a first implementation of the fix.

Right now, even if the data updates, the list doesn't scroll. That means that if new articles are added at the top, the scroll position doesn't change meaning that the new articles may push the content at the bottom without the view scrolling to the old article.

I'll try to make the view scroll back to the old articles without needing the Facebook implementation.

**Comment by aminecmi** [comment]
Hi,

Right now on the alpha channel, there is a first implementation of the fix.

Right now, even if the data updates, the list doesn't scroll. That means that if new articles are added at the top, the scroll position doesn't change meaning that the new articles may push the content at the bottom without the view scrolling to the old article.

I'll try to make the view scroll back to the old articles without needing the Facebook implementation.

**Comment by aancel** [comment]
Hello,
Thanks for the quick work !
Just a dumb question regarding alphas, can I access it to test it ?
I've subscribed to the beta channel on the Play Store, but for the alphas, wasn't there something via Google + ?
You can also put it on the release page of github, I don't have issues with sideloading apks.

**Comment by aminecmi** [comment]
Currently I'm the only one on the alpha. As the build and deployment is automated, I prefer the  alpha to be just for me to test if everything works. Regarding the beta, I never push to it because there is no one using it. I can do it if you'd like to be beta tester.

If you prefer to sideload, you can actually get the last APK (the alpha one) from the Jenkins page [here](https://jenkins.amine-bou.fr/job/ReaderForSelfoss/).

**Comment by aancel** [comment]
OK thanks for the information !
I've sideloaded the apks as beta releasing usually takes some time.
I'll take some time to test it and report back !
(I can already tell you had the right feeling about giving the user a hint about new updates with a "new updates available" button)

**Comment by aminecmi** [comment]
@aancel the "new update" feature is only available on the downloadable APK, as the Play Store will probably notify you when a new update is available.

**Comment by aancel** [comment]
A little feedback about the new version: I really like it this way !
It's a lot like I was browsing news with feedly previously, but self-hosted !
As you said before a way to indicate new updates and/or going to the top would be nice !
I've had several force close on a side note, but I was not able to reproduce them in a deterministic manner. It seems to be happening when my server was not available, but not really sure. I'll open an issue if I can pinpoint the issue !

**Comment by aminecmi** [comment]
Hi thanks for the feedback!

I'll add the new items indicator. If you want to go to the top, you can tap again on the current tab. It'll only scroll to the top without loading the new data.

I'm seeing a lot of crashes for an LG V20. It seems that I'm not receiving items from the API. Could you please install the beta version directly from the play store please, so you'll get the update (the update notification should be only used for the production updates) ? I'll try to handle this tonight and you'll have it by tomorrow.

**Comment by aminecmi** [comment]
I just pushed this to the release track. I'll add two new issues for the remaining tasks.

**Comment by aancel** [comment]
@aminecmi Ok, thanks for the updates and the associated development !
I did installed the beta version and it is working very well for me. I also noticed the behavior you describe in #172.
Thanks again for the great app !
