### ISSUE TITLE
Expand images on click in the webview

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#178]
[link](https://stackoverflow.com/a/33733098)

**Comment by MimaIsAwesome** [comment]
Hello, i would like to work on this issue. Can you assign me please?

**Comment by aminecmi** [comment]
@MimaIsAwesome  go ahead. I'll mark the issue as taken.

**Comment by MimaIsAwesome** [comment]
Thanks im on it. :)

**Comment by MimaIsAwesome** [comment]
Hello i am struggling with connection problems with JitPack, so i cant run android. 
Am i doing something wrong or are you aware of what is happening?

![image](https://user-images.githubusercontent.com/56257072/67010949-f41dff00-f0ee-11e9-85a9-2b7684fcc44d.png)

**Comment by aminecmi** [comment]
@MimaIsAwesome why would you need to connect to JitPack ?

I never had to, so I have no idea how to solve this, or even why you would need it.

**Comment by MimaIsAwesome** [comment]
in build.gradle you have maven url of this page with comment "//For likebutton only"

**Comment by aminecmi** [comment]
@MimaIsAwesome This should build without you needing to do anything.

Isn't it the case ?

**Comment by MimaIsAwesome** [comment]
i followed the instructions for download and installation of the project, but it seems this url have an issue to connect as a picture above, im getting this error and i dont know if the origin page have some issue (because if i just put url in browser it gives a page as an picture above) or im building it somehow wrong? 

![image](https://user-images.githubusercontent.com/56257072/67012988-a5726400-f0f2-11e9-8fa8-2d21ecb7ee75.png)

**Comment by aminecmi** [comment]
Maybe try [this](https://github.com/jitpack/jitpack.io/issues/3973) ?

**Comment by MimaIsAwesome** [comment]
ye thank you, it is maybe temporary

**Comment by MimaIsAwesome** [comment]
Problem solved, many people have the same issue, it was just needed to add "www" to link

**Comment by MimaIsAwesome** [comment]
Hello again, is there any chance i can private message you? I read that this feature is no longer 
available on git??

**Comment by aminecmi** [comment]
Hi,

What feature isn't available on git?
What would you want to talk about?

Le ven. 1 nov. 2019 à 17:26, MimaIsAwesome <notifications@github.com> a
écrit :

**Comment by aminecmi** [comment]
Closed in #315
