### ISSUE TITLE
Offline mode & sync support

### ISSUE THREAD

**Issue by jbfavre** [aminecmi/ReaderforSelfoss#179]
Currently, marking an article as read in the app trigger an HTTP request to the Selfoss API.
If you've no network, this call fails and you've to trigger it later.

I'd like to be able to work "offline", meaning performing any action I want/need.
When network is back, app will sync its state with the server one.
Article should be bulk marked as read

**Comment by jtojnar** [comment]
Hopefully, the api from https://github.com/SSilence/selfoss/pull/1014 could be re-used.

**Comment by jtojnar** [comment]
Feel free to comment on the PR with your requirements.

**Comment by aminecmi** [comment]
@jtojnar I didn't take a look at the PR yet. I was thinking that I would handle this locally as I still would need to make API calls.

**Comment by aminecmi** [comment]
@jtojnar I did look at the PR. The `sync` route will be helpfull, and easier to user as I was thinking to do. Thanks for the link.

**Comment by aminecmi** [comment]
@jbfavre the first things you asked for are now in testing. They should be deployed to beta tomorrow or later this week if I dont see any big issues.

The read/unread status sync with the server isn't done yet, but everything related to #33 is done.

**Comment by jbfavre** [comment]
@aminecmi thanks for the work !
I'll test this new version ASAP. But I guess I'll have to wait merge of SSilence/selfoss#1014 and the sync part to be able to fully test it

**Comment by aminecmi** [comment]
@jbfavre You could test the first part sooner !

I'll still have to support older versions of selfoss and emulate the sync feature, so you'll be able to test the sync-ish one soon and use the real one when it's available for your selfoss instance.

**Comment by jbfavre** [comment]
@aminecmi So, for now the offline mode is working but not the sync part, right ?
I'll test it as soon it's available, but does that means I'll have to mark items as read on both ReaderSelfoss & selfoss web app ?
If yes, I just hope the sync stuff will arrive soon :)

**Comment by aminecmi** [comment]
@jbfavre that's exactly it. I'll be working on the sync part now, so it may arrive soon too !

**Comment by aminecmi** [comment]
@jbfavre I'll close this issue because the "manual" sync is done. I'll open a new one with the selfoss call.
