### ISSUE TITLE
Wrong English translation.

### ISSUE THREAD

**Issue by 7twin** [aminecmi/ReaderforSelfoss#183]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?
* [ ] Did you read the `CONTRIBUTING` guide ?

### Description
Half the app is in indonesian

### Steps to Reproduce

1. Install App
2. Go through initial slideshow
3. Half the buttons, menus and settings are in indonesian (after setting up the server too)

**Expected behavior:** expected was that it would be in english, just like the other half of the app

**Actual behavior:** some parts are english, most are indonesian

### Device

- Device (manufacturer, model ...) Xiaomi Redmi Note 4
- OS (Android Version, ROM/Stock, Rooted/not, mods...) not rooted, stock, no mods, android 7
- App version _(See Prerequisites)_ newest from app store

**Comment by aminecmi** [comment]
Hi @7twin,

The app isn't completely translated in Indonesian, that's why some strings are still appearing in English.

If you want to, you can help translate the remaining strings (there's a link in the readme redirecting to the crowdin page).

**Comment by 7twin** [comment]
@aminecmi as described in expected behaviour, I am actually interested in the english version of it, not the indonesian one

**Comment by aminecmi** [comment]
@7twin for now, the app is in the language of your phone.

I could add an option to change that, but it's not a priority.

**Comment by 7twin** [comment]
@aminecmi my phone is set to english, I can't speak indonesian

**Comment by aminecmi** [comment]
@7twin, I finally understood.

Just tested it, and yes, there is an issue.

I'll try to fix this quickly.

**Comment by 7twin** [comment]
@aminecmi great, thanks! :relaxed:

**Comment by aminecmi** [comment]
@7twin I think I have found the issue. I uploaded a fix to the alpha channel. It will be pushed to the production channel later today.

**Comment by 7twin** [comment]
@aminecmi I'll make sure to download the update, as soon as it is available via appstore and report back if that fixed it, thanks again for such quick response.

**Comment by aminecmi** [comment]
Hi,

I just pushed the version to production. It should be available in a couple of hours.

It fixed the issue on my phone, could you check if it did with you too ?

Thanks.

**Comment by 7twin** [comment]
@aminecmi yes, it did, great job! after the update I think the english translation for the menu item: settings>article viewer>"mark articles as read when swipi • •" (yes the dots are in the middle) might have become too long (gets cut off), not sure if thats an issue, besides that it's done, thanks again!

**Comment by aminecmi** [comment]
@7twin Great! I'm gonna close this issue then.

Could you please open a new issue with the cut off text please ?
