### ISSUE TITLE
Setting cut off

### ISSUE THREAD

**Issue by 7twin** [aminecmi/ReaderforSelfoss#184]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?
* [ ] Did you read the `CONTRIBUTING` guide ?

### Description

The text is cut off, see below
settings>article viewer>"mark articles as read when swipi • •"

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/32747235/37609614-d0d85c92-2b9d-11e8-9ae9-6f1a30281c21.png)

### Device

- Device (manufacturer, model ...) Xiaomi Redmi Note 4
- OS (Android Version, ROM/Stock, Rooted/not, mods...) not rooted, stock, no mods, android 7
- App version (See Prerequisites) newest from app store

**Comment by alexa346** [comment]
I would like to give this a try if its still available?

**Comment by aminecmi** [comment]
@alexa346 yep go ahead.

I was thinking of having a smaller title and having the cut off text as subtitle. If you have another solution, don't hesitate.

**Comment by aminecmi** [comment]
@alexa346 any news on the issue ?

**Comment by aminecmi** [comment]
@alexa346 I'm gonna fix the issue myself.
If you still want to help, take issues from [here](https://github.com/aminecmi/ReaderforSelfoss/labels/Up%20For%20Grabs).
