### ISSUE TITLE
Title preview overlaps itself

### ISSUE THREAD

**Issue by 7twin** [aminecmi/ReaderforSelfoss#187]
See below

![Screenshot](https://i.imgur.com/xvwwrmE.jpg)

**Comment by aminecmi** [comment]
Can you post your device info please ? I can't reproduce this on my end with the same articles.

**Comment by 7twin** [comment]
@aminecmi 
- Device (manufacturer, model ...) Xiaomi Redmi Note 4
- OS (Android Version, ROM/Stock, Rooted/not, mods...) not rooted, stock, no mods, android 7
