### ISSUE TITLE
Build errror with Gradle

### ISSUE THREAD

**Issue by Rudloff** [aminecmi/ReaderforSelfoss#197]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

I'm getting an error when I try to build v1.6 with Gradle.

### Steps to Reproduce

1. `./gradlew assemble -P appLoginUrl="URL" -P appLoginUsername="LOGIN" -P appLoginPassword="PASS"`

**Expected behavior:** [What you expected to happen]
The app builds

**Actual behavior:** [What actually happened]
```
A problem occurred evaluating settings 'ReaderforSelfoss'.
> Ambiguous method overloading for method org.gradle.caching.http.HttpBuildCache_Decorated#setUrl.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        [class java.net.URL]
```

**Comment by aminecmi** [comment]
@Rudloff I just pushed a commit that should fix your issue.

**Comment by Rudloff** [comment]
Thanks! It builts correctly now.
