### ISSUE TITLE
Add unmark read button to internal viewer.

### ISSUE THREAD

**Issue by hsanson** [aminecmi/ReaderforSelfoss#208]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [ x Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

If we set the "Mark as read on swipe" option in the article viewer setting and we swipe over articles, these are marked as read, this is ok. But sometimes there are articles that require a more careful read latter so I would like to be able to mark it unread and continue to the next one.

Simply adding a unmark read icon, next to the mark favorite in the article viewer suffices.

**Comment by aminecmi** [comment]
This might be tricky, because the "read"  status is only set when swiping to the next item.

Thanks for the request !

**Comment by hsanson** [comment]
Actually that is something I would like to see changed. The article should be marked read when it is loaded in the article viewer. This is the same as the Selfoss client does and would allow to implement a unmark read action that I find way more important for usability.

**Comment by aminecmi** [comment]
@hsanson it was the case first, but I found myself accidentally going back to the previous activity and having to search for the article in the "all" tab.

Not really sure if I want to change this for now.
