### ISSUE TITLE
Links not opening directly

### ISSUE THREAD

**Issue by GutHib** [aminecmi/ReaderforSelfoss#228]
Hi,

I just upgraded to the newest version of the reader. Previously the links would open directly with a single click. Now, when i click on one of the items, i get some kind of toolbar instead. I looked into settings to see if this can be corrected, but when i scroll down, the last word i see is "actions" - the options to actually change these actions are missing.

Great app, thanks for all the hard work you are putting into it. Hoping that previous functionality can be restored.

**Comment by aminecmi** [comment]
Hello,

There was previously an option to switch this behavior.

For now, you could change the displaying to card view, or long press on the article.

**Comment by GutHib** [comment]
Card view works, thanks.

Just for reference, without the card view, theres another bug, as the toolbar appears to be popping up randomly in other entries as well when you return from the preview in the local browser.

**Comment by aminecmi** [comment]
@GutHib this is fixed now. 

Still, it won't be available just yet as I want it to come with #1 that I'm currently testing.

You'll be able to change back to the list view on the next update.

**Comment by GutHib** [comment]
Awesome - thank you.
