### ISSUE TITLE
Use Vector Image instead of png

### ISSUE THREAD

**Issue by Binnette** [aminecmi/ReaderforSelfoss#249]
Hi Amine,

Can I replace all png icons with vector images ?
png images are time consumming for maintenance and current icons have not the exact same size.

Here are screenshots showing that icons do not have the exact same pixel count:
![image](https://user-images.githubusercontent.com/6597721/48955528-ac2e4080-ef4e-11e8-8366-1bbea1085f5b.png)

![image](https://user-images.githubusercontent.com/6597721/48955583-e39ced00-ef4e-11e8-86f2-19d6d579f217.png)

Note that vector images are supported in Android 5.0+ (API 21+) while ReaderforSelfoss minSDK is 16+
But there is a very simple "backward compatibility solution" ([see here](https://developer.android.com/guide/topics/graphics/vector-drawable-resources))

Can you please just say "GO" to me and i will work on this ?

**Comment by aminecmi** [comment]
@Binnette Ok with me !

**Comment by Binnette** [comment]
Here is another bug that i want to fix.

In dark theme, settings icon are mostly invisibles:
![image](https://user-images.githubusercontent.com/6597721/48956589-201f1780-ef54-11e8-97b0-df0443644d7c.png)

**Comment by aminecmi** [comment]
@Binnette I imported them from Android Studio 
<img width="267" alt="capture d ecran 2018-11-23 a 19 36 50" src="https://user-images.githubusercontent.com/510304/48957148-2ebafe00-ef57-11e8-95de-813377c2cd9f.png">

**Comment by aminecmi** [comment]
These are material icons. They should be available from https://www.google.com/design/icons/

**Comment by aminecmi** [comment]
@Binnette I started using vectors in the new commits. (see #257) 

I added them to the `any-dpi` folder.

**Comment by Binnette** [comment]
Nice, feel free to pick any vector from my fork.
It works nicely on Android 6.0, but i do not test it on others Android versions.
