### ISSUE TITLE
Allow Http Auth without a Selfoss User Account

### ISSUE THREAD

**Issue by c64bob** [aminecmi/ReaderforSelfoss#251]
I would like to use Http Auth on my selfhosted selfoss instance, but since I am the only user, I don't want to configure a user account in selfoss. When adding my server to the app, it complains if I only configure Http Auth, without providing a selfoss username and password. This is implemented here:
https://github.com/aminecmi/ReaderforSelfoss/blob/1d9a440ae7ce887f074e134867e244de03864b27/app/src/main/java/apps/amine/bou/readerforselfoss/LoginActivity.kt#L166-L168

Could you allow using Http Auth on its own?

**Comment by aminecmi** [comment]
Hi @c64bob,
It's a code bug. You should be able to connect via HTTP only.
I'll correct this today.
The update should be available a few hours after.

**Comment by aminecmi** [comment]
@c64bob Done !

It'll be available in a few hours or tomorrow.

**Comment by aminecmi** [comment]
@c64bob should be available in a couple of hours. It's deployed on the play store.
