### ISSUE TITLE
reader style

### ISSUE THREAD

**Issue by quite** [aminecmi/ReaderforSelfoss#257]
The bultin reader uses "justify" on paragraphs (it has an even right margin). I would be grateful if this could be tweaked, turned off. I find that it does't really increase readability. Thoughts?

**Comment by aminecmi** [comment]
Hi @quite,
What would be the tweaks you would want to see in the reader style ?

**Comment by quite** [comment]
Sorry for not being clear. I just think the "justify" style on the paragraphs is needless. In inline-css, I guess it's: `<p style="align: justify">`

**Comment by aminecmi** [comment]
Understood.

I'll try to add an option for this.

**Comment by aminecmi** [comment]
@quite Done !
Should be available soon.

**Comment by aminecmi** [comment]
@licaon-kter I'm currently deploying a version. You can remove the prebuild from the f-droid metadata.

**Comment by aminecmi** [comment]
Which release are you talking about? The play store one that I have control on, or the fdroid ?

Now, the version changed so the fdroid builder will have the new version when it runs.

I'll deploy it to the play store production in a few hours or tomorrow.

**Comment by licaon-kter** [comment]
@aminecmi Github release of course.

**Comment by aminecmi** [comment]
@licaon-kter well the release was created and is available for build.

**Comment by aminecmi** [comment]
@licaon-kter Yep that's the one.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/commit/c63b0c63c5fc9e4560280f506ffcc90473c6c412 ;)

**Comment by aminecmi** [comment]
Great! Thanks!

**Comment by aminecmi** [comment]
@quite it is.
You should have a new icon on the top right of the article viewer.
![screenshot_1544823308](https://user-images.githubusercontent.com/510304/50028606-8b5a8780-fff0-11e8-8273-17788a13a16a.png)

**Comment by quite** [comment]
Ah thanks! :)
