### ISSUE TITLE
Customize text display

### ISSUE THREAD

**Issue by mtarnawsky** [aminecmi/ReaderforSelfoss#261]
I've been trying out the app today - I'm finding it a little bit hard to read, though.  The text feels very tightly bunched together, both horizontally and vertically.  

One of the nice things I can do on  various e-reader apps is to choose font, font size, and line spacing.  If it was possible to do something similar with this app, it would make it look so much more appealing and easier to read.  Thanks!

**Comment by aminecmi** [comment]
Hi, thanks for the feature request.

The app has one of the requested things you asked for: the font size changing in the settings.


I'll do the remaining things.

What would be the font you would want to see/choose from ?

**Comment by mtarnawsky** [comment]
Thanks.  Roboto and Google Sans would be handy, and given that they're Google fonts, should hopefully be available on modern Android devices.

**Comment by aminecmi** [comment]
@mtarnawsky this isn't going well...

Here is the result for now  
![screenshot_1544823308](https://user-images.githubusercontent.com/510304/50028880-60bcfe80-fff1-11e8-9741-39c1f2c09632.png)

As I'm using a webview to display the content of the article, there does not seem to be a simple/working way to change the font. I'll see what I can do.

**Comment by mtarnawsky** [comment]
Thanks for giving it a go - appreciated even if you ran into some issues!

**Comment by aminecmi** [comment]
@mtarnawsky I'll still try, but if I can't update the webview font, there is no need to have any other part of the app to be customizable. I'll keep you posted.

**Comment by aminecmi** [comment]
@mtarnawsky I'm working on a workaround. The webview will use css fonts.

It's the only thing that is working.

This should be in beta soon, and I'll try to let it like this for a while before pushing it to production build.

**Comment by aminecmi** [comment]
The font is done. The font size was available, and I just raised the line height for now. If you want the ability to change it, please open another issue.

**Comment by aminecmi** [comment]
@mtarnawsky deployed to production.

**Comment by mtarnawsky** [comment]
@aminecmi : Just tried it out - looks much better. Thanks!
