### ISSUE TITLE
Hide tags with 0 articles

### ISSUE THREAD

**Issue by phxql** [aminecmi/ReaderforSelfoss#264]
Hi,

first I'd like to thank you for your work.

I propose a feature: in the main screen, when opening the drawer on the left, there is the list of tags. Even the tags which have 0 articles in it appear in this list, with the same badge color as tags which have articles in it.

It would be great if the either the tags with 0 articles are hidden or if the badge is removed or gets a different color.

What do you think?

**Comment by aminecmi** [comment]
Should be available in a couple of hours.
