### ISSUE TITLE
favicons not working with basic auth

### ISSUE THREAD

**Issue by c64bob** [aminecmi/ReaderforSelfoss#266]
Favicons are not being displayed when I am using basic auth with my selfoss instance (just basic auth, no selfoss username/password). I see lots of 401 answers in my nginx log with no authentication. Is there a chance you could add the basic auth info to the favicons requests as well?

**Comment by aminecmi** [comment]
@c64bob this should be deployed.

**Comment by c64bob** [comment]
> @c64bob this should be deployed.

Thank you, that was super fast! Will test in a couple of days
