### ISSUE TITLE
Self signed certificat issue when swiping to mark as read.

### ISSUE THREAD

**Issue by phxql** [aminecmi/ReaderforSelfoss#270]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

As far as i know, there is no possibility to mark a single article as read - only a button to mark all articles as read. What do you think about adding a button to mark a single article (in article view) as read?

**Comment by aminecmi** [comment]
@phxql thanks for the feature request.

Actually, you can. You can swipe items to mark them as read.

It this the feature you are looking for ?

**Comment by phxql** [comment]
I have opened a tag which contain 1 article. Neither swiping right nor left works. Am I missing a setting somewhere?

**Comment by aminecmi** [comment]
@phxql you can swipe items on either sides, either with a selected tag or source or not, but only on the "unread" tab.

#269 should let you mark them on the "All" tab too.

**Comment by phxql** [comment]
Ah, i get it - i can swipe the article in the list view. I tried to swipe it in the article view! Thanks for clarification.

**Comment by aminecmi** [comment]
@phxql you can mark them as read too when viewing them in the article viewer, and in that case, there is a setting you need to enable that is in Settings > Article Viewer > Mark as read on swipe (or something like this)

**Comment by phxql** [comment]
I found that setting, but this doesn't work on articles which are in a tag with 1 article, as you can't swipe left or right.

**Comment by aminecmi** [comment]
@phxql Weird. It actually works for me.

What version of the app are you running ? On what device ?

**Comment by phxql** [comment]
1. find a tag with 1 article in it
2. click on the article so that it opens in the article viewer (there is one white dot displayed at the top)
3. try swiping left or right
4. nothing happens ("Mark as read on swipe" is switched on in the settings)

App version is 1719010051-store, Phone is a OnePlus 5T with Android 9.

**Comment by aminecmi** [comment]
@phxql I can't reproduce your issue. [Here is what happens for me](https://drive.google.com/file/d/1q4nc_hACixiGgx9Yf8uVaAV36BRd2BJe/view?usp=sharing).

> I would love to have the option to mark that item as read without switching back to list view and swipe the list item right or left.

You should be able to do it. As you can see on my video. That's what should happen.

Can you share a screen capture of what happens for you ?

**Comment by aminecmi** [comment]
@phxql Any news on the issue.

Just trie it, and can't reproduce it at all.

**Comment by phxql** [comment]
I can't reproduce it, because the app crashes when opening an article. After i got the update which fixes this, i'll try again with debug logging. Should i paste the debug id here?

**Comment by aminecmi** [comment]
@phxql Ok !

Yes you can past the debug id here when you can.

**Comment by phxql** [comment]
I just enabled both settings and swiped two articles. Debug id is 7c7e6eef-928a-4b66-b984-c1197efbd978

**Comment by aminecmi** [comment]
Thanks.

Are you using a self signed certificate ?

This seems to be the error: 
```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found
```

**Comment by phxql** [comment]
Yes, i use a self-signed certificate. This hasn't been a problem before, fetching articles and mark them manually as read works for example.

**Comment by aminecmi** [comment]
@phxql Ok, I'll look into this. This may take some time because I'll have to install a new instance, and configure a self-signed cert.

**Comment by phxql** [comment]
If you want, i'll set something up. I already have all the self-signed cert stuff in place.

**Comment by aminecmi** [comment]
@phxql that would be super useful.

**Comment by aminecmi** [comment]
@phxql in fact, I don't think it will be after all.

I found the issue. It's a bug that I solved. Again, it should be available in 2 or 3 hours.

**Comment by aminecmi** [comment]
@phxql finally deployed to production!

**Comment by phxql** [comment]
It works, thanks a lot for your work!

**Comment by aminecmi** [comment]
No problem at all.

Thanks for taking the time to report the issue.
