### ISSUE TITLE
Marking all articles as read doesn't update count badge in left drawer

### ISSUE THREAD

**Issue by phxql** [aminecmi/ReaderforSelfoss#271]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Steps to Reproduce

1. view articles in list view for a tag
2. click on the "Mark all as read"
3. open left drawer

**Expected behavior:** 

Badge with count for that tag disappears

**Actual behavior:**

Badge with count for tag is still there, with wrong number of unreads

**Comment by aminecmi** [comment]
Thanks for the feature request !

This will be fixed soon.

**Comment by aminecmi** [comment]
@phxql deployed to production.
