### ISSUE TITLE
App crashes every time i open an article

### ISSUE THREAD

**Issue by phxql** [aminecmi/ReaderforSelfoss#275]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

Open any article, and the app crashes. The "report bug to developer" window opens, i click okay - no idea if you ever got any report, the app just closes without any confirmation.

### Steps to Reproduce

1. Select article in list
2. Crash

**Expected behavior:** [What you expected to happen]
Displays the article, doesn't crash

**Actual behavior:** [What actually happened]
Crashes.

### Device

- Device (manufacturer, model ...): OnePlus 5T
- OS (Android Version, ROM/Stock, Rooted/not, mods...): Android 9
- App version _(See Prerequisites)_: 1719010131-store

**Comment by aminecmi** [comment]
Hi @phxql ,

There seems to be an issue with fonts loading for you, maybe something blocking the font downloading.
For now I pushed a fix for your issue that should be available in a couple of hours.

**Comment by phxql** [comment]
Thanks!

**Comment by aminecmi** [comment]
Deployed. Will be available soon.
