### ISSUE TITLE
App reloads when sharing from the HomeActivity

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#277]
When sharing an article from the homeactivity, the whole list reloads.

This is pretty frustrating and confusing.

**Comment by DroidSU** [comment]
Hello is this issue resolved? Would like to work on it..

**Comment by aminecmi** [comment]
@DroidSU nope. Go ahead and have fun.

**Comment by aminecmi** [comment]
@DroidSU still working on the issue ?
