### ISSUE TITLE
Feature Request: Sort unread tags to top / hide tags with 0 articles

### ISSUE THREAD

**Issue by phxql** [aminecmi/ReaderforSelfoss#279]
Hi,

i have another feature suggestion, maybe toggable in the settings:

when I open the left drawer which shows the tags (and i have a lot of tags), i have to scroll the tag list to find the tags with unread articles. It would be great if the tags with unread articles would be sorted on top (or just hide the tags with no unread articles). That way i won't have to scroll through the tab list.

What do you think?

**Comment by phxql** [comment]
Thanks a lot!

**Comment by aminecmi** [comment]
Keep them coming !
