### ISSUE TITLE
Remove the timeout log

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#281]
There is no need to always log the timeout errors.

Find a way to intercept retrofit timeout errors and don't log them.

**Comment by hector2** [comment]
Can i do this?

**Comment by aminecmi** [comment]
@hector2 go ahead !

**Comment by hector2** [comment]
hey @aminecmi can you give me an example in which this timeout error occurs? I tried shutting down my selfoss instance and then trying to refresh the sources, and it showed a toast with "The update didn't work, try again later, or check your selfoss logs"

**Comment by aminecmi** [comment]
@hector2 the issue is that Acra (the bug tracker) was sending a lot of errors because of the timeout.

If you want to test it, in the experimental settings, you could try to configure your timeout to 1 second and make any call, this should log a lot of things, including acra trying to send the logs.

**Comment by hector2** [comment]
@aminecmi ok i'll try that thx! I was thinking about implementing our own http HttpLoggingInterceptor so wen can control better what errors to log. What do you think?

**Comment by aminecmi** [comment]
@hector2 I think that's what I tried. But yeah, I don't see another way to do so :)
