### ISSUE TITLE
The top bar occupying too much space

### ISSUE THREAD

**Issue by toyqiu** [aminecmi/ReaderforSelfoss#282]
### Prerequisites

* [yes] Are you running the latest version?
* [yes] Did you check for an existing issue ?
* [yes] Are you reporting to the correct repository?
* [yes] Did you perform a cursory search?
* [yes] Did you read the `CONTRIBUTING` guide ?

### Description

[Description of the bug or feature]
The top bar occupying too much space
I think the top bar could be less high or hidden when at reading page.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Screenshots (optional)

`...`

### Device 

- Device (Sumsung Galaxy Note 8)
- OS (Android Version 8.0, ROM/Stock, Rooted/not, mods...)
- App version _(See Prerequisites)_

**Comment by aminecmi** [comment]
Hi @toyqiu 

Do you have any screenshot ?

**Comment by toyqiu** [comment]
![Screenshot_20190317-180648_Reader for Selfoss](https://user-images.githubusercontent.com/479873/54488741-6839bf80-48e0-11e9-9c60-3d9e0423439a.jpg)
the green top bar

And I don't know why the article part became black background since a week agon.
Nothing has been changed in setting,it's totally normal since I've been using it for about one year.
And I've tried uninstalling the app and reinstalling it,it keeps black background in article part.

**Comment by aminecmi** [comment]
@toyqiu the top bar size is standard. It should be kept as it contains actions.

What I could try to do, is to hide it on scroll.

Concerning your other issue, this is likely related to an update of your browser or webview component. Could you please try using a dark theme to solve this, and get back to me ?

**Comment by toyqiu** [comment]
> @toyqiu the top bar size is standard. It should be kept as it contains actions.
> 
> What I could try to do, is to hide it on scroll.
> 
> Concerning your other issue, this is likely related to an update of your browser or webview component. Could you please try using a dark theme to solve this, and get back to me ?

![Screenshot_20190317-182758_Reader for Selfoss](https://user-images.githubusercontent.com/479873/54488981-9d471180-48e2-11e9-9977-5ecd99d0a49f.jpg)

Yes,hiding it on scroll is great!
Using a dark theme makes the words readable.
Any possible could you fix it? the article part still feels strange.
Thank you very much for responding!

**Comment by aminecmi** [comment]
@toyqiu I'm seeing the dark background issue now.

As I can reproduce it, it'll be easier for me to fix it.
