### ISSUE TITLE
"Mark all read" only works once for each app start

### ISSUE THREAD

**Issue by lapete** [aminecmi/ReaderforSelfoss#283]
Somehow related to #192  ? 

### Description

When I open the app, I can only use the "mark all read" button in the top right corner once (e.g. for a specific tag or source). After that, it won't work for another tag or source, I have to restart the app in order to get it working again (once).

### Steps to Reproduce

1. Open the app "fresh" (terminate if already running)
2. Go to a source with unread entries
3. Hit the top right button to mark all read. All entries will be marked read
4. Go to another source with unread entries
5. Hit the button again. Nothing will happen.

**Expected behavior:** [What you expected to happen]
All entries in all sources where I hit the button are marked read.

**Actual behavior:** [What actually happened]
Only the entries in the first source where I hit the button are marked read.

### Device

- Device: Xiaomi Mi A1
- OS: Android 9, Security patch level February 5, 2019
- App version: 1719010301-github

**Comment by lapete** [comment]
This does not longer happen since a while, maybe solved as a side effect from another update.

**Comment by aminecmi** [comment]
Ok, thanks. Closing this then.
