### ISSUE TITLE
Crash on start since last release

### ISSUE THREAD

**Issue by Ezwen** [aminecmi/ReaderforSelfoss#286]
### Description

Since the last update, when I tap on the app to start it, it instantly crashes.

### Steps to Reproduce

1. Install/update the app to 1719051321
2. Start the app from the launcher

**Expected behavior:** the app should start

**Actual behavior:** the app starts to load (I can see the splash screen with the icon), then crashes without any warning or error message.

### Device

- Device (manufacturer, model ...): Wiko RIDGE 4G
- OS (Android Version, ROM/Stock, Rooted/not, mods...): Stock rom, Android  5.0.2, rooted, all system Google packages and apps were removed by myself using root
- App version _(See Prerequisites)_ : 1719051321

**Comment by aminecmi** [comment]
Thanks for the report.

I'll take of it tonight.

**Comment by shaneonabike** [comment]
Mine seems to crash as it is fetching new news. I'm on an LG Android

**Comment by aminecmi** [comment]
@Ezwen @shaneonabike The issue should be fixed with this [apk](https://github.com/aminecmi/ReaderforSelfoss/releases/download/v1719051372/app-githubConfig-release.apk).
You may need to reinstall the app and reconfigure it since it will be another signing key as the selfoss one.

**Comment by aminecmi** [comment]
Sorry about that !

**Comment by Ezwen** [comment]
> Sorry about that !

No problem, thanks for the quick fix and for the app :)

**Comment by aminecmi** [comment]
@Ezwen Thank **you** for the report.

**Comment by shaneonabike** [comment]
Woooooo hooo it's been fixed hooray!

**Comment by StyXman** [comment]
I started getting the same on v1720020321 from F-Droid for some weeks now. I don't think it was right after the latest update (I don have the date sorry). Should I reinstall too? I see nothing very damning in `logcat`'s output. This is Android 7.1.2 on FairPhone2.

**Comment by aminecmi** [comment]
Hi @StyXman 

That's super weird.

Does this happen every time ? Did you change some setting before this ?

This shouldn't be the same issue, but still.

**Comment by StyXman** [comment]
> Does this happen every time ? 

Every time on the phone. I just fresh installed it on a tablet and it works.

> Did you change some setting before this ?

I can't remember, but I would say no.

**Comment by aminecmi** [comment]
@StyXman So, it worked before, right ? Before any update ?

If you don't see anything from the logs, maybe try reinstalling.

**Comment by StyXman** [comment]
I has been working since... I don't know. Can I ask android when I first installed something? `logcat` shows 3 lines `IInputConnectorWrapper: finishComposingText on inactive InputConnection`, then `reportFullscreesnMode on inexistant InputConnection`, then the other message again. Does that help?

**Comment by aminecmi** [comment]
@StyXman Not really...

And I don't think it would show anything. I'm not sure.

Can you try reinstalling and let me know if that solved the issue ?

**Comment by StyXman** [comment]
Yeah, that worked :-S

**Comment by aminecmi** [comment]
Great ! If it does happen, don't hesitate to open a new issue.
