### ISSUE TITLE
Listview doesn't fit

### ISSUE THREAD

**Issue by Offerel** [aminecmi/ReaderforSelfoss#287]
It seems that the listview doesn't fit correctly. ![](https://i.imgur.com/ggui09V.jpg)

I have added a screenshot, ti give you a small idea what i mean. The text is cut off.

**Comment by aminecmi** [comment]
@Offerel thanks for the report.

I'll take a look at this.

In the meantime, you can use the card view that has no issue at all.

**Comment by Offerel** [comment]
Not a real big issue for me. I use Selfoss now since 4h for the first time. If i find more, i will report it. I like the project really. I have tried tt-rss and I'm really surprised how fast selfoss is, compared to tt-rss on a raspberry pi. I work as a softwaretester, so i think i will found the one or other issue and report it. Hopefully a little bit more detailed as in this first example.

**Comment by aminecmi** [comment]
@Offerel No problem at all.

It helps a lot having people report issues !

**Comment by aminecmi** [comment]
@Offerel why did you close this ?

**Comment by Offerel** [comment]
I changed to a other phone and didn't use the app. Other OS
