### ISSUE TITLE
[FR] Display image instead of favicon in list/cardview

### ISSUE THREAD

**Issue by Offerel** [aminecmi/ReaderforSelfoss#288]
I would like to ask, if it possible to display a article picture, instead of the favicon in the ListView?

**Comment by aminecmi** [comment]
Hello, 

In the list view, an image is displayed if it's available. If it's not, the source icon is displayed.

If there is no image displayed, you may want to check the selfoss spout settings.

**Comment by aminecmi** [comment]
I'll close this because it's already works like this.

Don't hesitate to submit new issues or feature requests.

**Comment by Offerel** [comment]
Sorry. But i think in that case, it's a bug. Since I'm still testing different clients and possibilities to switch from Inoreader to something self-hosted, I installed another Selfoss app fr.ydelouis.selfoss at the same time. For the same source the pictures in the article list are shown in this app. In apps.amine.bou.readerforselfoss only the favicons are shown. Same sources, same URL, same credentials. Selfoss is version 2.18.

Maybe I have only set something wrong but I don't know what that should be.

**Comment by aminecmi** [comment]
Maybe the other app fetches the image from the article content.

Mine does display the image sent by selfoss.

For any item, you could see yourself if there is one displayed on the web version. If not, then I don't display one either.

**Comment by Offerel** [comment]
I understand. If I'm at the web, a image is displayed. But the source of the image is a external URL (i assume provided by the feed or the feed article), not the domain of my Selfoss instance. Since I'm testing, i use temporary only a SQLite DB (will switch later to MariaDB). Is there some way, to configure the feeds that way, to retrieve also the images in the feed and deliver them from my own server?

Most of the spouts of my feeds are set to "RSS Feed" and a handful others to "RSS Feed (with FullTextRSS)", but thats only the case 10% of my subscribed feeds.

Im really new to Selfoss, so please forgive me to ask such maybe stupid questions.

**Comment by aminecmi** [comment]
@Offerel these issues are not related to the app.

If you have a question with Selfoss itself, you should ask them [here](https://github.com/SSilence/selfoss)
