### ISSUE TITLE
App's back button within a sub-menu of Settings exits the Settings

### ISSUE THREAD

**Issue by gunr2171** [aminecmi/ReaderforSelfoss#290]
### Prerequisites

* [x] Are you running the latest version?
  I am running 1719051372-github, installed through F-Droid
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
  I sure hope so.
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?
  Seeing this is low-priority, I'll try not to bump this.

### Description

When inside the Settings menu, and sub-menus, there are two ways to "go back". First is the App's own "back" button at the top-left. The second is using the OS's navigation bar at the bottom of the phone.

If you are inside a sub-menu of Settings, pressing the App's back button will take you completely out of Settings, while the OS's back button will bring you back to the root of the Settings (if you are only one level deep).

### Steps to Reproduce

**Setup for both methods (run these steps before running either option below)**
1. Close and open the app to some "main screen" (something that isn't the Settings)
2. Click the hamburger menu in the top left
3. Tap Settings
4. Tap General

**Using the OS's back button**
1. Run setup steps if you haven't already
2. Tap the OS's back button at the bottom of the device
3. Notice that you are at the root menu of Settings

**Using the App's back button**
1. Run setup steps if you haven't already
2. Tap the App's back button at the top left of the screen
3. Notice that you are back at the app's "main screen", NOT the root menu of Settings

**Expected behavior:**
I would expect both the App's back button and the OS's back button to perform the same navigation action (preferably putting me at the root of the Settings menu).

**Actual behavior:**

* The OS's back button moves back one screen.
* The App's back button leaves the Settings.

### Video

https://youtu.be/1D5gKu1pFas

The video shows the navigation actions at different depths of the Settings, using the different back buttons. The "broken" behavior using the App's back button starts at 12 seconds, and the "fixed" behavior with the OS's back button at 20 seconds.

### Device

- Device: OnePlus 6
- OS: OxygenOS 9.0.8 (Android 9 - security August 2019)
- App version: 1719051372-github

**Comment by aminecmi** [comment]
Hi @gunr2171 

Thanks a LOT for the specific bug report.

I'll look into this !
