### ISSUE TITLE
Question: how does needConfigmation() work?

### ISSUE THREAD

**Issue by StyXman** [aminecmi/ReaderforSelfoss#292]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?
* [ ] Did you read the `CONTRIBUTING` guide ?

### Description

I'm a developer with not much free time (two kids are tiring). I use this app everyday, and it happened to me twice already that all posts are masked as read. Of course, I suspect that I accidentally hit the button in the upper right corner. Given #180 and 320924b4ed076c5356f534648f964269cf3bfda4 I understand that there must be a dialog asking for confirmation, but that doesn't seem to happen (I can accidentally hit one button, but not two in a row and missing a dialog). So, how is this supposed to work?

### Device

- Device: Fairphone 2
- OS: Android 7
- App version: latest on F-Droid

**Comment by aminecmi** [comment]
Hi,

First or all, thanks for using the app 😀.

The "bug" you're describing never happened to me, and seems really strange. 

`needsConfirmation` will show a dialog. If the the confirm button is pressed, all articles will be marked as read. If not, the nothing will happen.

If you're able to reproduce, please let me know.

**Comment by StyXman** [comment]
I just did. No dialog. How can I help you? I have almost no Android experience.

**Comment by aminecmi** [comment]
Can you maybe give me your exact Android version? I'll try to reproduce.

Can you please also check the version number of the app ?

**Comment by StyXman** [comment]
On Sun, Dec 08, 2019 at 05:45:34AM -0800, Amine Bou wrote:
> Can you maybe give me your exact Android version? I'll try to reproduce.

    Android 7.1.2 SPL Aug01 2019 (FP build number 19.08.1)

> Can you please also check the version number of the app ?

    0.8.3 from f-droid.

**Comment by aminecmi** [comment]
This is not the last version.

The last one is "version 1719051372-github".

I'm not even sure there was a 0.8.3 version.

**Comment by aminecmi** [comment]
@StyXman any update on the app version?

**Comment by StyXman** [comment]
I'm sorry, I got the wrong app.

**Comment by aminecmi** [comment]
@StyXman is it a selfoss reader too?

**Comment by StyXman** [comment]
yeap, but I can't find it in f-droid anymore. Maybe I should try this one :)

**Comment by aminecmi** [comment]
Feel free to do so!

**Comment by StyXman** [comment]
BTW, the dialog is right there :)
