### ISSUE TITLE
Feature Request: Change dark gray text background to the same gray

### ISSUE THREAD

**Issue by TobiasDev** [aminecmi/ReaderforSelfoss#293]
I'm using this app with my Selfoss instance and I really love it! The only small UI thing that bothers me is the darker gray background since the text has no whitespace at all inside of it. If possible I would love to see this background in the same gray color (as the one around it) or maybe making it a user setting like the other colors. :) 

I've added a screenshot to show where I mean. 

![Screenshot_20200127-202749_Reader_for_Selfoss](https://user-images.githubusercontent.com/5912371/73212916-805cab00-414f-11ea-8755-97bb5bebb97d.png)

Keep up the great work!

**Comment by aminecmi** [comment]
Hello,

Thanks for the feature request.

If I remember correctly, I did try to use the same color for the content background, but I was having a lot of issues with this.

I'll try to look into it !

**Comment by TobiasDev** [comment]
Sounds awesome! Thanks.

**Comment by aminecmi** [comment]
@TobiasDev d370ddc4d1a681dfd940bfe941effc6972b49470 should fix your issue !

It should be available via f-droid in a couple of days.
