### ISSUE TITLE
[help!] Which URL to use? Or is something else not correct?

### ISSUE THREAD

**Issue by madb1lly** [aminecmi/ReaderforSelfoss#294]
### Prerequisites

* [y] Are you running the latest version?
* [y] Did you check for an existing issue ?
* [y] Are you reporting to the correct repository?
* [y] Did you perform a cursory search?
* [y] Did you read the `CONTRIBUTING` guide ?

### Description

This may not be the place for support questions, but I don't know where else to ask:

I can't login to selfoss on my hosted instance. I'm sure I've got the username and password right, so that leaves the URL. I access the web interface of Selfoss through http://domain/selfoss/. When I put that URL it doesn't work, I get a message to check my details again.

Is there something on the Selfoss side I need to configure, or should I use a different URL?

FYI I'm using latest app from F-Droid running on Android 9 on a Nokia 8. My selfoss instance is installed from Softaculous on a free hosted subdomain of rf.gd from InfinityBest. I'm using HTTP as I can't set up an SSL certificate on this service.

Cheers 🙂

**Comment by aminecmi** [comment]
Hello @madb1lly ,

If you access your selfoss instance via the url http://domain/selfoss/, the url set in the app should be the same.

Is there any way you could see in the selfoss logs if there is an issue ?

Are you using some kind of HTTP authentication that would block the api call ? BASIC or DIGEST ?

**Comment by madb1lly** [comment]
Hi @aminecmi,

Thanks for your reply. Which logs do you mean? I can't access the system logs if that's what you mean. In default.log the only error messages relate to feeds which can't be accessed or are invalid (from when I originally imported the OPML).

I changed the logging level in config.ini to EMERGENCY but it didn't add anything to the log. Which logging level should I use?

Thanks 🙂

**Comment by aminecmi** [comment]
@madb1lly I was talking about the default.log file.
Maybe check your Apache logs to see if the call is arriving to your server ?

**Comment by aminecmi** [comment]
Closing this until more details.

**Comment by madb1lly** [comment]
Hi @aminecmi,
Sorry for not getting back to you. I discovered that the hosting service I was using was blocking this because it's only intended for hosting basic web pages, not services of any kind.
Cheers 🙂
