### ISSUE TITLE
Timezone weirdness

### ISSUE THREAD

**Issue by deathbybandaid** [aminecmi/ReaderforSelfoss#296]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

Time of article entry is incorrect between app and selfoss.
Often time is in the future.

The below screenshots were taken back to back

### Screenshots (optional)

![Screenshot_20200402-220802_Firefox](https://user-images.githubusercontent.com/18010545/78316785-821b6400-752e-11ea-80b5-ee2f255232b5.jpg)
![Screenshot_20200402-220654_Reader for Selfoss](https://user-images.githubusercontent.com/18010545/78316796-89427200-752e-11ea-8445-c2a0cf64dd7b.jpg)

### Device

- stock pie s8active
- App version _(See Prerequisites)_

**Comment by davidoskky** [comment]
This is solved for selfoss 2.19
It cannot be solved in selfoss 2.18 as the timezone of the server is not provided by the api.
