### ISSUE TITLE
Thumbnails in Articles List

### ISSUE THREAD

**Issue by sonicnkt** [aminecmi/ReaderforSelfoss#297]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
* [X] Did you read the `CONTRIBUTING` guide ?

### Description

I really like selfoss and this opensource reader.
What i would really love to see tho in the future is an option for preview thumbnails in the list/cards view if the feed item contains an image. This should of course be optional since some user would probably not like it but i kind of miss them coming from my old RSS App. 

I have added an image of the old selfoss app in the playstore which had this feature but is to unstable to be used today.

### Screenshots (optional)
![Image of old selfoss app](https://lh3.googleusercontent.com/Gehxr5W-A10Zkap0alceCqMIU9smMy-nHn0GW5msNrWtR2BTdxLMd8RoXV7_68dZqis=w2560-h1304)

**Comment by aminecmi** [comment]
@sonicnkt this isn't the right repo.

**Comment by sonicnkt** [comment]
Isn't this the official repo for the android app "Reader for Selfoss" (on F-Droid)? The Screenshot fro mthe other app was only posted as reference and should show how it could be implemented visually.

**Comment by aminecmi** [comment]
Oh ok @sonicnkt .

Sorry about that. I only read the title and saw the screenshot, and I thought you were talking about the old selfoss app.

Now that I read your issue, I can tell you that I tried to solve this issue "locally", but I didn't find an efficient way to do it. 
I think that should be handled on the selfoss webapp side. I created a selfoss spout that find the main image inside the html, and returns it in the right api field.

**Comment by aminecmi** [comment]
![Screenshot_20200428-155200](https://user-images.githubusercontent.com/510304/80495606-6e65f080-8968-11ea-8608-e4fb9fd27d26.jpg)
This is the result

**Comment by sonicnkt** [comment]
No Problem.
Haha that looks a bit messy :) I also noticed that many embedded rss images are often very low res.  I guess to make it look fine you have to keep those displayed as small as possible.  
The display method of the old app might be a better solution for most sources. 

This is just me but even good res images this size would be to big in the articles card overview as you could only show 1-2 images on normal devices on the screen at a time and it wouldnt be a lot different than swiping through the articles.

I have no experience on android development but i created a small mockup in gimp of how i would imagine it.  The thumbnails are the first image of the feed article, resized to a fixed width and height so it looks a bit more pleasing and with the the small size it does not look that "warped" even if the ratio was changed quite a lot. I have included an article without an embedded image. 

![git_selfoss_01](https://user-images.githubusercontent.com/5454622/80500430-7fb1fb80-896e-11ea-973e-2c7f566b263e.jpg)

![git_selfoss_02](https://user-images.githubusercontent.com/5454622/80500445-8476af80-896e-11ea-81cd-a3462969393b.jpg)

This is using the list view mode but should be fine in card mode as well, maybe scale the thumbnails a bit bigger.


So there should be also a server side change that sets the thumbnail image?

**Comment by aminecmi** [comment]
![Screenshot_20200428-170054](https://user-images.githubusercontent.com/510304/80503303-f69cc380-8971-11ea-9635-cd170353e05a.jpg)

**Comment by aminecmi** [comment]
![Screenshot_20200428-170308](https://user-images.githubusercontent.com/510304/80503447-28158f00-8972-11ea-8d01-0b9a7c6d4cd0.jpg)

**Comment by sonicnkt** [comment]
Wow impressed with the fast test builds 😃 

The first images in the list view screenshot you posted are a bit smaller and are not scaled up which also moves the text a bit to the left. Is it complicated to scale every image to the same size with fixed ration (1x1) maybe cropping  images to 1x1 would problably look even better but it dont know how complicated that would be to implement.

Card view looks great. I could imagine have two colums of those on bigger devices like tablets would look very good as well 😉 

Thanks again for the fast replies!

**Comment by aminecmi** [comment]
![Screenshot_20200428-172454](https://user-images.githubusercontent.com/510304/80505876-344f1b80-8975-11ea-8a6c-db7e2b927338.jpg)

**Comment by aminecmi** [comment]
So, in the end, the enhancements you would like would be better handling of images ?

**Comment by sonicnkt** [comment]
ah sorry i havent checked the app on my tablet yet as i am just in the process of moving everything over to selfoss. 

Yes feature request would be implemetation of thumbnails in List and Card view.
Your card view screenshots look very good allready, nothing to add here.
For list view i would love to to see the  feed icon added (like in the mockup i posted) and having all the images uniformly scaled so the list view looks a bit more tidy.

That would be my wishlist.

PS:  is there a way to donate something for your work!

**Comment by aminecmi** [comment]
I'll try to handle picture a little bette, then.

Thanks for wanting to help. I just set up a way for people to donate. 

The link is now on the project page.

**Comment by sonicnkt** [comment]
Got some time today and got a bit more familiar with selfoss (server) and found out that thumbnails are not created for normal rss feads. And i understand now why this would require a serverside change as well. Since normal images inside the articles are not stored on the server it would not be possible to have them in the article lists/cards. 
But the proposed changes are still valid  tho, have to get in contact with the server devs to implement the rest 😄 

PS: i tried the app on my tablet now and since its a small device i was wondering if it would be possible to set the number of columns by hand in a future release. Using List Mode i would prefer to have only one column on my 8inch tablet as everything looks a bit crowded. 

PPS: Enjoy your croissants!

**Comment by aminecmi** [comment]
I could share my spout if you'd like !

And yeah, I could add the column number thing. It was an option before, but I don't know why I removed it.

And again, thanks for the croissants !

**Comment by sonicnkt** [comment]
i would love to try the spout, is it for normal rrs only or also for the fulltext scraper? 
Does it need a specific version? im currently running a 2.19-snapshot that is a few month old as i could not get the latest one working at all.

**Comment by aminecmi** [comment]
It's just a simple thing that does everythings as the "RSS Feed" but fetches the image. I'm using the same version I think, so it should work.

```
<?php

namespace spouts\rss;

/**
 * Spout for fetching images from given rss feed
 *
 
class images extends feed {
    /** @var string name of spout */
    public $name = 'RSS Feed Images';

    /** @var string description of this source type */
    public $description = 'Fetch images from given rss feed.';

    /**
     * returns the thumbnail of this item (for multimedia feeds)
     *
     * @return mixed thumbnail data
     */
    public function getThumbnail() {
        if ($this->items === null || $this->valid() === false) {
            return '';
        }

        $item = current($this->items);

        // search enclosures (media tags)
        if (count(@$item->get_enclosures()) > 0) {
            // thumbnail given?
            if (@$item->get_enclosure(0)->get_thumbnail()) {
                return @$item->get_enclosure(0)->get_thumbnail();
            }

            // link given?
            elseif (@$item->get_enclosure(0)->get_link()) {
                return @$item->get_enclosure(0)->get_link();
            }
        } else { // no enclosures: search image link in content
            $image = \helpers\Image::findFirstImageSource(@$item->get_content());
            if ($image !== null) {
                return $image;
            }
        }

        return '';
    }
}
```

**Comment by sonicnkt** [comment]
Thanks, it seems tho that i had this allready in my spouts directory. And it gives me the desired result.
Wondering now how i could add this to the fulltext-rss spout, but my php skills are almost nonexistent 😄 

btw, i had the same problem with some thumbnails in list view not scaling correctly like in your screenshot. This seems to be some kind of rendering bug. Because when i turn off the screen and then on again they now scale correctly:
![thumbnail_rendering_01](https://user-images.githubusercontent.com/5454622/80638744-37273a80-8a61-11ea-8ef1-e6da38562265.jpg)
![thumbnail_rendering_02](https://user-images.githubusercontent.com/5454622/80638761-3b535800-8a61-11ea-9bca-c3ab896db5f8.jpg)

An Option to disable thumbnails in the builtin article Viewer would be nice as well as it just shows the image twice in many articles:
![thumbnail_articel_view](https://user-images.githubusercontent.com/5454622/80639172-e9f79880-8a61-11ea-81dd-0a91dbb8852c.jpg)

**Comment by sonicnkt** [comment]
after using your app now a bit longer i found a few more ui issues, if it ok i will create a new clean issues in github with the things i noticed . This on is getting a bit off topic and crowded.

**Comment by aminecmi** [comment]
No problem. If it's okay with you, I'll close this one.

And maybe open one issue for each issue, it would be easier to find for other people.

**Comment by sonicnkt** [comment]
Ok that make sense.
