### ISSUE TITLE
Issue with Thumbnail rendering in List View

### ISSUE THREAD

**Issue by sonicnkt** [aminecmi/ReaderforSelfoss#298]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
* [X] Did you read the `CONTRIBUTING` guide ?

### Description

Often thumbnails seem to be rendered as feed icons in list view. This sometimes can be fixed with scrolling the list up and down or turning the screen off and on.

I can confirm this behavior on multiple devices running different versions of android.

In the screenshots below you can see the issue and how it fixed itself.

### Suggestion
Based upon this i think it would be a good idea to change the rendering of all listview items so it looks a bit more cleanly, i have attached a mockup of this as a suggestion. All text is rendered with the same margin to left. Feed icons are centered.

I think it looks a bit cleaner this way but maybe other would prefer the current method.

### Screenshots:

Rendering issue:
![thumbnail_issue_listview](https://user-images.githubusercontent.com/5454622/80714166-cf223400-8af4-11ea-9423-152be72dc10f.jpg)

### Mockup:
Mockup of cleaner list view:
![sr_mockup_listview_2](https://user-images.githubusercontent.com/5454622/80714261-f5e06a80-8af4-11ea-8bbd-b337694ca369.jpg)

**Comment by aminecmi** [comment]
Should be fixed with #314
