### ISSUE TITLE
Release app on F-Droid

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#3]
asked by @klundry on the old repository

**Comment by jtojnar** [comment]
Someone was askin about F-Droid on [reddit](https://www.reddit.com/r/selfhosted/comments/6qritc/your_most_used_selfhosted_applications/dkzpl8k/) today.

I wanted to try to package the app but I [could not make their build server run](https://gitlab.com/fdroid/fdroidserver/issues/356).

**Comment by aminecmi** [comment]
I think I had the same issue, and didn't want to waste time debugging this.

Are you taking care of this issue @jtojnar ?

**Comment by jtojnar** [comment]
Not anymore. Maybe it would be faster to request packaging on https://gitlab.com/fdroid/rfp/issues, though you would probably need to streamline the build a little more.

What non-free components does the app use? I count

* Fabric for analysis
* Firebase for analysis
* Mercury for article formatting

Would it be possible to not include non-free components if the variables are not specified, see the [Inclusion Policy](https://f-droid.org/docs/Inclusion_Policy/).

The analysis code could probably be removed without any harm. Removing Mercury would be inconvenient, either switching to a free fallback or allowing users to specify a custom key in preferences.

**Comment by aminecmi** [comment]
Yeah, I saw that they don't accept analytics tools. I have to check how to build the app without Firebase and Fabric (I'll add an issue for that).

Still, I don't think it's a priority for now. The apk is available from the releases page on github, or from jenkins.

**Comment by aminecmi** [comment]
As I commented [here](https://github.com/aminecmi/ReaderforSelfoss/issues/59#issuecomment-320010331), one of the many things that can't be done with F-Droid builds, is crash reporting/tracking.

Users will never send them to me, they'll just uninstall the app and even give it a one stare rating without much explanation.

I won't spend this much time trying to remove the deps from my app, if an alternative doesn't exist.

The source code and the build steps are available => The user can build the app himself.
There is an apk generated and available from jenkins, and github, and using firebase, you'll know when an update is ready.
The app is on the play store.

As I don't see any other reason to have an "incomplete" build on F-droid, I wont do it.

**Comment by jtojnar** [comment]
F-Droid does not forbid phoning home completely, it just does not like using proprietary tracking mechanisms. They recommend using something called [Acra](http://www.acra.ch/), of course setting it up is extra work.

**Comment by aminecmi** [comment]
Because of/thanks to RGPD, I may remove every Firebase or Fabric dependencies, and then be able to deploy the app to fdroid.

**Comment by aminecmi** [comment]
As #59 is fixed. The only missing thing is Mercury api.

**Comment by aminecmi** [comment]
Mercury api is removed.

**Comment by aminecmi** [comment]
Request done [here](https://gitlab.com/fdroid/rfp/issues/585).

**Comment by aminecmi** [comment]
[App available!](https://f-droid.org/fr/packages/apps.amine.bou.readerforselfoss/)

**Comment by gpion** [comment]
Link not working on my phone (Galaxy S7, Oreo): F-Droid app launches and display an _"application not found"_ toast.
Anyway, Play Store version is OK. so not a big deal.

**Comment by aminecmi** [comment]
@gpion [this is shared from the app](Reader for Selfoss (RSS reader for Selfoss) - https://f-droid.org/app/apps.amine.bou.readerforselfoss).

If it doesn't work, the issue comes from f-droid.

**Comment by rEnr3n** [comment]
@gpion Works for me. You need to update your repo manually if you set `Automatic update interval` to `Never`.

**Comment by gpion** [comment]
The problem was a conflict with the already installed Play Store version.
Everything's fine now
