### ISSUE TITLE
Ampersand & not displayed in heading of builtin article viewer

### ISSUE THREAD

**Issue by sonicnkt** [aminecmi/ReaderforSelfoss#300]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
* [X] Did you read the `CONTRIBUTING` guide ?

### Description

Ampersand Symbol (&) gets displayed as escaped version in the Heading with the internal article viewer but gets displayed correctly in the list/card view. 

### Screenshots
![issue_ampersand_1](https://user-images.githubusercontent.com/5454622/80984159-cb145000-8e2d-11ea-8b80-22eb176aad32.jpg)
![issue_ampersand_2](https://user-images.githubusercontent.com/5454622/80984170-cd76aa00-8e2d-11ea-8723-f7048bec133f.jpg)

**Comment by aminecmi** [comment]
Thanks, I'll look into this !

**Comment by namanrana16** [comment]
I would like to work on it, can you assign it to me?

**Comment by aminecmi** [comment]
@namanrana16 it’s all yours.

**Comment by aminecmi** [comment]
@namanrana16 are you still working on this ?
