### ISSUE TITLE
Do not save read articles

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderforSelfoss#305]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

I really like the possibility to save articles for offline reading.
It is in fact very useful to me as often I do not have internet connection.
My problem is that not all the articles get saved: only the most recent ones.
I assume this is a hard limit on the number of articles, in order to limit memory usage.
This behavior is fine to me: I do not need hundreds of articles to read offline, but just a few.

The problem is that read articles are saved as well and considered into the count of articles, therefore if I read all the recent articles no old unread articles will be saved as the memory is filled with the read ones.
I generally get 2-3 unread articles saved, and often none.
I do not really care about reading again articles i read already, and if I do that is seldom enough that I can justify connecting to the internet to do that.
I would therefore like to have an option to exclude read articles to be saved for offline reading.

**Comment by aminecmi** [comment]
Hello @davidoskky ,

If I remember correctly, if you enable background sync, all the unread articles will be saved for offline reading, and every favourited one.

There isn’t any count limit for saved articles, **BUT**, there might be something to do with the number of articles you load from the selfoss instance. I can take a look at this when I can.

Can you maybe see what’s the number you set, and the number of articles that you see when opening the app without connection?

**Comment by davidoskky** [comment]
In my settings background sync is enabled. I have the number of loaded articles from selfoss set to 200.
Right now I have saved offline:
- 5 unread articles
- 45 read articles
- 0 favorites

It adds up to 50 total articles, this makes me think of a hard limit in the number of available downloaded articles. It could otherwise be set to 1/4 of the 200 loaded articles.

**Comment by aminecmi** [comment]
I look into this, then.

Thanks for the report.

**Comment by aminecmi** [comment]
@davidoskky I just read the code, and what I do is get all the items, without specifying a count, and store them. 

The number of articles may be set with the `items_perpage` [parameter](https://selfoss.aditu.de/#configuration_params) in your selfoss instance. 

I will change this, and save all the favourites ones, and the new ones only.

**Comment by davidoskky** [comment]
I can confirm this: my items_perpage parameter was in fact set at 50.
I set it at 100 and the articles saved offline are now 100; this still does not solve the issue as 95 are read and only 5 unread.
I'd be very thankful if you could be able to solve the issue saving all the unread ones!

**Comment by aminecmi** [comment]
Yep, I’ll think of a way to handle this.

**Comment by davidoskky** [comment]
This was solved in #331 at least for how I interpret it.
I will close the issue.
