### ISSUE TITLE
Timeout marking articles as read with Offline mode

### ISSUE THREAD

**Issue by jbfavre** [aminecmi/ReaderforSelfoss#308]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

After enabling offline mode and loading articles, marking them as read turns into timeout with error message `Impossible de marquer l'article comme lu` (Unable to mark article as read).
Checking on Selfoss Web UI, article are indeed marked as read.

After "some" time, ReaderforSelfoss succeed marking articles as read (connection reuse issue ? timeout ?).

Same goes for starring article and refreshing article list.

Unfortunately, I didn't see any thing relevant in application logs.

Please note that:
* I don't have this timeout with my Selfoss instance Web UI.
* debuger doesn't seems to be available (`Not starting debugger since process cannot load the jdwp agent.` in logs)

### Steps to Reproduce

1. Enable Offline mode
2. Load articles
3. Try to mark some as read, swiping right or left

**Expected behavior:**
Article should be mark as read without error message

**Actual behavior:**
Error message `Impossible de marquer l'article comme lu`, `Impossible de marquer l'article comme favoris` or `Impossible de récupérer les nouveaux éléments` is displayed (sorry, I use french translation)

### Device

- Device: Google Pixel 4a
- OS: Android 11, google version, no mods or root
- App version 1720020321-github

**Comment by aminecmi** [comment]
Hi @jbfavre and sorry for the delay.

I couldn't recreate your issue, but it seems that forcing offline mode when launching the app, and trying to read articles does indeed try to make an api call.

Do you have a video of the issue, so I can try to recreate the issue on my end ?

Thanks for the report.

**Comment by jbfavre** [comment]
Hello @aminecmi 
Thanks for answering and no problem for the delay.

Some stats about my SelfOSS instances to give you more context:
* 425 sources
* 433019 items (16015 starred)
* Running on a quite low server (only 1G of RAM)

Now, about hte issue:

1. Api call with (or despite of) offline mode enabled is the expected behaviour as far as I know.
Offline mode has been enabled in https://github.com/aminecmi/ReaderforSelfoss/issues/179 without the `sync` call.
And I'm not sure the selfoss release I'm running supports it (note for myself: update selfoss)

2. Digging into the issue, I figured out HTTP 499 responses in my access logs.
This means the client has closed the connection.
Looking into the app, I found the API timeout option in experimental. After increasing it to 30 seconds, HTTP 499 became HTTP 504 (server side timeout instead of client ones). **So it appears client app is not the culprit.**

3. Looking into the database, I found plenty of SQL statement waiting for `table lock`, which the way one can write into a MyISAM table: write operations on MyISAM table requires table level lock.
I altered items table to use InnoDB engine, which enable row level lock, and it now (**almost**) works.
**So far so good, now I got no timeout anymore while marking items as read.**

**But**:
When lauching the app, it perform some requests as shown in access logs:

    [15/Nov/2020:07:44:09 +0000] "GET /tags?username=XXXXXXXXXX&password=XXXXXXXXXX HTTP/2.0" 200 640 "-" "okhttp/3.9.0" https
    [15/Nov/2020:07:44:12 +0000] "GET /items?type=unread&username=XXXXXXXXXX&password=XXXXXXXXXX&items=200&offset=0 HTTP/2.0" 200 178686 "-" "okhttp/3.9.0" https
    [15/Nov/2020:07:44:39 +0000] "GET /sources/list?username=XXXXXXXXXX&password=XXXXXXXXXX HTTP/2.0" 504 176 "-" "okhttp/3.9.0" https
    [15/Nov/2020:07:44:43 +0000] "GET /items?username=XXXXXXXXXX&password=XXXXXXXXXX HTTP/2.0" 504 176 "-" "okhttp/3.9.0" https

2 requests are done for items. One for unread, another one for last 100 items.
SQL statement for last 100 items is:

    SELECT items.id, datetime, items.title AS title, content, unread, starred, shared, source, thumbnail, icon, uid, link, updatetime, author, sources.title as sourcetitle, sources.tags as tags
    FROM items AS items, sources AS sources
    WHERE items.source=sources.id AND TRUE ORDER BY items.datetime DESC, items.id DESC LIMIT 100 OFFSET 0

I can see 2 problems here:
* Default mobile app configuration loads 200 items, not 100. I think we're missing something there
* `[personal opinion]` I think we should load only unread items. This would avoid 1 request at each updates.

Another issue is the `source/list` request, which makes an heavy SQL statement:

    SELECT
        sources.id, sources.title, sources.tags, sources.spout,
        sources.params, sources.filter, sources.error, sources.lastentry,
        sourceicons.icon AS icon
    FROM sources AS sources
    LEFT OUTER JOIN
        (SELECT items.source, icon
         FROM items AS items,
              (SELECT source, MAX(id) as maxid
               FROM items AS items
               WHERE icon IS NOT NULL AND icon != ''
               GROUP BY items.source) AS icons
         WHERE items.id=icons.maxid AND items.source=icons.source
         ) AS sourceicons
        ON sources.id=sourceicons.source
    ORDER BY sources.error DESC, lower(sources.title)

I'm not sure about the usefulness of this statement. Besides, it uses ORDER whithout proper indexes :-1: 
Anyway, it's server side so no need of discussing it here (thought such statement should be used at school as a "DON'T EVER DO IT" example ;) ).
But I think an option to disable loading sources list could be usefull

As a summary:
1. When experiencing timeouts while marking articles as read, one should check on SQL server to ensure it uses InnoDB engine for items table.
2. We should enlight the API timeout option
3. In order to get a more reliable mobile app, and less stressful for server, maybe we could have an option to disable loading sources list

**Comment by aminecmi** [comment]
> Api call with (or despite of) offline mode enabled is the expected behaviour as far as I know.


Not really. I’m not using the selfoss sync and offline mode, but a homemade offline mode that stores the actions done and execute them when the app is not in offline mode. The manual triggering of the offline mode may be the issue here.


> Default mobile app configuration loads 200 items, not 100. I think we're missing something there

This may be a configuration thing server side. Could you check if you have the value of 200 actually set on the app ?


> [personal opinion] I think we should load only unread items. This would avoid 1 request at each updates.

I can check but if I remember correctly, this is because of the offline mode. One more api call is made so the data is stored.


> But I think an option to disable loading sources list could be usefull

That make sens. Could you open a new issue for this, please ?


> When experiencing timeouts while marking articles as read, one should check on SQL server to ensure it uses InnoDB engine for items table.


This may need to be reported on the selfoss project. I’m not sure the app should do anything about this.

> We should enlight the API timeout option

What do you mean by this ?


> In order to get a more reliable mobile app, and less stressful for server, maybe we could have an option to disable loading sources list

Yep, good idea.

**Comment by jbfavre** [comment]
> Not really. I’m not using the selfoss sync and offline mode, but a homemade offline mode that stores the actions done and execute them when the app is not in offline mode. The manual triggering of the offline mode may be the issue here.

I know you don't use sync API. But, my understanding was that your custom offline mode only store articles content, not actions on them.
Besides, I have enabled offline mode at first configuration and never changed it.

> This may be a configuration thing server side. Could you check if you have the value of 200 actually set on the app ?

Yes I do. The point is, the request made by the app does not specify item number, therefore using server side default which is 100 in my case.
You should pass `items` param when requesting items (currently only done for unreads)

> I can check but if I remember correctly, this is because of the offline mode. One more api call is made so the data is stored.

Which, in my opinion is quite unfortunate. I think there might be something to dig in here to optimize (ie. reduce) APi calls

> Could you open a new issue for this, please ?

Sure !

> This may need to be reported on the selfoss project. I’m not sure the app should do anything about this.

I mentioned it for the record :) 
I agree this is more a server issue here.

> What do you mean by this ?

API timeout option is "hidden" into experimental parameters and I didn't saw it at first.
More, there doesn't seem to be any default value specified.
