### ISSUE TITLE
Make source and tag list loading configurable

### ISSUE THREAD

**Issue by jbfavre** [aminecmi/ReaderforSelfoss#309]
### Prerequisites

* [X] Are you running the latest version?
* [X] Did you check for an existing issue ?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?
* [X] Did you read the `CONTRIBUTING` guide ?

### Description

When refreshing article list, the app also refreshes sources and tags.
Problem is, calling `/sources/list` performs a quite heavy and non optimized SQL statement on server side (described in #308).

On some setup, it can lead to server timeout errors (but the SQL statement still runs).
The mobile app is not accountable for such statement, but I think we could provide a workaround to not execute them.

I'd like to be able to disable `tags` and `sources` refresh in `ReaderforSelfoss` configuration (for example in `General > Display`) as it can be done for unread count.

**Comment by davidoskky** [comment]
I will be working on this, do you believe an update sources button could be useful? I may add that to the side drawer so that one could manually update sources after he added a new one.

**Comment by aminecmi** [comment]
@davidoskky they are loaded pretty much every time you open the app.

**Comment by davidoskky** [comment]
Alright, then there's no need for that!

**Comment by aminecmi** [comment]
@davidoskky having this button would mean, when some option is selected, loading the sources and tags once, and caching them. The button would refresh the cash.

@jbfavre would this behavior work for you ?

**Comment by aminecmi** [comment]
Should be available in version `1721030811` when it's available on fdroid.
