### ISSUE TITLE
Garbled output when scrolling 

### ISSUE THREAD

**Issue by michix** [aminecmi/ReaderforSelfoss#319]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [ ] Did you read the `CONTRIBUTING` guide ?

### Description

It regularly happens that scrolling through a news item the output is garbled. Sometimes it 8s even garbled immediately. The problem is then solved by going back the home screen and then going back to the app. 

### Steps to Reproduce

I cannot reproduce it deterministically. However, it appears appropriately every 10th item or so. Sometimes more often, sometimes less. 

### Screenshots (optional)

![Screenshot_20201213_221151_apps amine bou readerforselfoss](https://user-images.githubusercontent.com/5859234/102024228-1530bd00-3d91-11eb-963c-86027ab15604.jpg)

### Device

- Huawei p30
- Android 10, Emui 10.1.0 - but I also had it with android 9 and on an Huawei P Smart 2016 with Android 8
- App Version 1719010271-store

**Comment by aminecmi** [comment]
This seems to be a duplicate of #285 

Could you maybe check if the info in the original case helps you ?

**Comment by michix** [comment]
Many thanks for the quick reply. In fact, it looks like that this issue is a duplicate to #285. However, I'm having WebView 87 installed and the problem still persists. I understood that the version of WebView was the solution in #285.

**Comment by aminecmi** [comment]
Did you try to check if the webview used is the chrome one ? This may be the issue.

I can’t really help with this, as it is a Android issue, and I don’t have any control on this. All I could do is open an issue on the Android tracker, but not sure that would be fixed anytime soon.

If you have the up to date system webview, and that’s what is selected in your settings, you should disable the article viewer and use the internal browser to see the articles.

**Comment by michaelmejaeger** [comment]
In the developer options I see that only WebView is available as the WebView implementation. I understand that you cannot do anything about it. Since it seems that I am the only one having this problem, I guess you should not bother. It's probably a Huawei thing... Anyway, many thanks for your support and your great work!

**Comment by aminecmi** [comment]
@michix just to let you know. You seem to be using an old version of my app.

Could you try updating it please ?

You'll find the updated version on fdroid, and it should be 1720020321-github.

**Comment by michix** [comment]
Aaarrgh, sorry, it seems like I had the old version from play store installed. Many thanks for this hint! I guess,the problem is solved now, I will check the next days. 

Many, many thanks!

**Comment by aminecmi** [comment]
No problem.

Tell me if the issue is still present for you on the newer version.

I opened an issue on the google tracker [here](https://issuetracker.google.com/issues/175488699).

**Comment by michix** [comment]
The issue is solved with the newest version from fdroid. Many thanks!
