### ISSUE TITLE
app crashes after selfoss-update to selfoss-2.19-e6e1ba7 (current dev)

### ISSUE THREAD

**Issue by herrxyz** [aminecmi/ReaderforSelfoss#320]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

app crashes 1 or 2 sec after loading new content, before you are able to scroll in app or open an entry
as it was working with older selfoss instance, I dont think its related to device

### Steps to Reproduce
1. install (or upgrade to) selfoss-2.19-e6e1ba7
(1.5 deleted all app data, entered new url, login,...)
2. open app, will load content (including new content)
3. app just crashes

### Device
- Device Xiaomi Mi Note 10 Pro
- OS Stock MUI Global 12.0.3 stable
- App version 1720020321-github
- Selfoss version: crashing with selfoss-2.19-e6e1ba7, was working fine with selfoss 2.19-2f46fd8

**Comment by herrxyz** [comment]
selfoss instance with logging "debug" does not show any errors, only several successful logins with username and password

**Comment by aminecmi** [comment]
@herrxyz thanks for the report.

Did you try the new version available on f-droid ? 

You can even download the apk from [here](https://f-droid.org/en/packages/apps.amine.bou.readerforselfoss/).

If that does not fix the issue, I'll have to check this.

**Comment by herrxyz** [comment]
thank you very much for your fast reply
shame on me, didn't see the new version, its working like a charm now
unfortunately, my f-droid-app didn't update repos, maybe due to battery savings, so I thought I have the most recent version (checked it before reporting, but only in app with outdated sources :( )
