### ISSUE TITLE
Do not fetch articles every time the home is opened

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderforSelfoss#334]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

Right now if you open an article and then go back to the home, all articles are fetched.
This is annoying as I open one article, read it go back and open another one.
Every time I want to switch between two articles I have to wait for the app to complete the fetching of the articles.

I would prefer if the app only fetched the articles when it's opened and then I can choose to update the articles through the pull gesture.
Would it be possible and desired to avoid updating the items every time the home activity is displayed?

Another way to fix this issue for my use case would be to add a read/unread button in the top bar, near the favorite one; this way I could swipe through the articles and mark the ones I read as read without need to go back to the home activity.

**Comment by aminecmi** [comment]
This is the same as https://github.com/aminecmi/ReaderforSelfoss/issues/277

**Comment by davidoskky** [comment]
Oh, sorry! I thought that was specifically about the share button; I will close this issue then.
Today I'll take a look to see what can be done to prevent this behaviour.
