### ISSUE TITLE
Application unusable on phones with api 16

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderforSelfoss#339]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

While testing for #338 I tried running the app in a simulated image running api 16, which I believe is the oldest one supported by this app.
The app opens, though when inserting the url of the selfoss instance this message appears "Oops. You may need to add a \ at the end of the url."
There is no way to enter the url and thus the app is unusable.

Of course after trying on my fork I did try on master as well and the issue is still there.

**Comment by davidoskky** [comment]
This is a problem with `Patterns.WEB_URL`, it doesn't match the Top Level Domains that have been recently added.
I guess this could be fixed changing how that check works, but I'm not sure if that's worth it...

**Comment by aminecmi** [comment]
This is super old.

No one ever reported it.

We could change the minSdk, but that should be it.
