### ISSUE TITLE
Descending sorting

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderforSelfoss#379]
### Description

It would be nice to have an option to sort the articles from the oldest to the newest.
This is not my use case, but I can imagine someone with a lot of articles which should be read in publication order.
For example a story that is published in different episodes, or a news website.
Sorting from the oldest to the newest would save time and make the experience more straightforward as they can immediately recognize which one is the oldest unread and start from there.

I imagine it would be enough to include this option for unread articles only.
I'm not sure wether it would be better to add an option in the settings to enable this or to add a button to the interface.
Adding a button to the interface would allow a quick change according to what the user wants to do at the moment, however the interface is already pretty crowded; I guess it could be added under the ellipsis menu.

**Comment by aminecmi** [comment]
I think that this is a selfoss configuration.

I’ll have to check if this can be changed via the api calls.

**Comment by davidoskky** [comment]
It is right, this behavior is included in the selfoss settings.
I guess it would be redundant to add this feature to the app then.
