### ISSUE TITLE
Login page in dark mode

### ISSUE THREAD

**Issue by davidoskky** [aminecmi/ReaderforSelfoss#394]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?
* [x] Did you read the `CONTRIBUTING` guide ?

### Description

The login page in dark mode has dark text over dark background

### Steps to Reproduce

1. Login
2. Set dark mode
3. Logout

### Screenshots
![Screenshot_2022-01-07-18-17-24-055_apps amine bou readerforselfoss](https://user-images.githubusercontent.com/13107368/148581912-0b366cb3-8b29-4709-a7ee-46ed35f43461.jpg)

**Comment by aminecmi** [comment]
The login page should always be in light mode.

The logout button should delete all the settings (like the dark/light setting).
