### ISSUE TITLE
"Loaded Item Numbers" didn't work anymore

### ISSUE THREAD

**Issue by Kanten** [aminecmi/ReaderforSelfoss#402]
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check for an existing issue ?
* [x] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?
* [ ] Did you read the `CONTRIBUTING` guide ?

### Description

After the last update, the Number of Articles to shown in the App can be set to, for example, 25 in the "Loaded Items Number" but this entry will be ignored. If there are more than 25 News on the server, the app show them all in a row.
I cleared the app Cache and reinstalled the app. No difference.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Screenshots (optional)

`...`

### Device

- Device (manufacturer, model ...) Google pixel 3
- OS (Android Version, ROM/Stock, Rooted/not, mods...) Stock Android 12
- App version _(See Prerequisites)_ 1722010141-github.

**Comment by davidoskky** [comment]
I can reproduce this problem, I'll fix it soon.
