### ISSUE TITLE
Could not get unknown property 'appLoginUrl'

### ISSUE THREAD

**Issue by jtojnar** [aminecmi/ReaderforSelfoss#58]
I opened the project in Android Studio and received the following error:

```
Error:(64, 0) Could not get unknown property 'appLoginUrl' for BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=/home/jtojnar/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=/home/jtojnar/.android/debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
<a href="openFile:/home/jtojnar/ReaderforSelfoss/app/build.gradle">Open File</a>
```

**Comment by aminecmi** [comment]
These are variables I added to run the espresso tests. I'll update the readme.

**Comment by aminecmi** [comment]
@jtojnar I updated the contribution guide. You should have all you need to build the app. You can reopen if it's still not working.

**Comment by jtojnar** [comment]
Sorry, I have not build Android applications for a several years (the last Android I used was Ice Cream Sendwich). Where do the `-P` arguments go?

**Comment by aminecmi** [comment]
[This may help you](https://stackoverflow.com/questions/33216248/passing-p-parameters-to-gradle-from-android-studio/36509321) if you just want to generate an apk, just run `gradle assemble` followed by the parameters.
