### ISSUE TITLE
Intro icons have too low resolution + Revert to old icon

### ISSUE THREAD

**Issue by jtojnar** [aminecmi/ReaderforSelfoss#64]
I have just installed the app and the first thing I saw were hideously blurred icons in the intro – well the new app icon is horrible in any resolution but enlarged like this, it is simply abhorrent. Does Android support vector icons yet? It would be much nicer.

**Comment by aminecmi** [comment]
Hi,

I think I'll revert to the old icon anyway.
I just need to find a way to disable the ugly white round that's added.

If I remember correctly, it was also pixelated with the old icon, I'll find something better to fix this.

Thanks for posting this.

**Comment by aminecmi** [comment]
@jtojnar it's in testing. It should be out in the following days.

**Comment by jtojnar** [comment]
It looks infinitely nicer. Thanks.
