### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by knight-shade** [aminecmi/ReaderforSelfoss#75]
**Doubt regarding parameters value.**
Hey @aminecmi ,
Trying to get ReaderforSelfoss up and running in android studio, got the Mercury API key and added my email as feedbackEmail, have some queries regarding it:
I have no idea what the value for other parameters should be, which are:
1. sourceUrl
2. trackerUrl
3. Do I need to add vales for appLoginUrl, appLoginUsername and appLoginPassword? If yes, what they should be?

![capture](https://user-images.githubusercontent.com/20313518/31071062-490ada34-a780-11e7-909c-fb37be41c528.PNG)

`...`

**Comment by aminecmi** [comment]
Hey @knight-shade ,

The sourceUrl and trackerUrl are the url of the source code, and the url of the issue tracker. 
They can be empty, the only thing that won't work is that the settings links wont work.

Regarding appLoginUrl, appLoginUsername and appLoginPassword, they're only used for the tests, so you can keep them empty, or use your own selfoss instance url, username and password.

I'll update the contribution guide to explain this.

Thanks for letting me know.

**Comment by knight-shade** [comment]
Thank you @aminecmi
