### ISSUE TITLE
Internationalization.

### ISSUE THREAD

**Issue by knight-shade** [aminecmi/ReaderforSelfoss#77]
Hey @aminecmi , can I make translate the app into other languages except FR and NL and make a pull request?

**Comment by aminecmi** [comment]
Hi @knight-shade ,

Sure ! You're more than welcome to add translations to the app.
You can easily add it via [crowdin](https://crowdin.com/project/readerforselfoss).

**Comment by knight-shade** [comment]
@aminecmi , Just completed translation for Danish. Is it all right?

**Comment by aminecmi** [comment]
Thanks so much @knight-shade ! Thanks for translating the play store listing strings too !

I'll try to push the update with the danish translation today, or at least this week end.

Again, thanks for your help.

**Comment by knight-shade** [comment]
Love to help @aminecmi , looking forward to complete the remaining translations. Just wanted to know if you are fine with me making the pull request in translation since I am taking part in Hacktoberfest  and it requires me to make minimum of 4 pull request. I would be glade if you are on-board with the idea. Let me know how to make pull request if you are okay with it. :)

**Comment by aminecmi** [comment]
No problem. You could also make any other pull request !

**Comment by aminecmi** [comment]
Hi @knight-shade according to crowdin, there seems to be some issues with the translations, and a lot of the translations are just the suggested by Microsoft.
Are you sure you speak danish ? Not to be rude, but crowdin reported a lot of issues.

**Comment by knight-shade** [comment]
Hi @aminecmi , nope I don't speak Danish, I speak English. I used Google Translate to get the danish translation for all the strings. Are the danish translation not up to mark?

**Comment by aminecmi** [comment]
@knight-shade only translate if you speak the language, please.

Google translate and other translation tools aren't perfect (I could have done that myself), and I want it to be translated by people speaking the language.

I'll close the issue now. Open another one if you need. And please, only translate to languages you speak fluently.
