### ISSUE TITLE
Easy access to the layout style switch.

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#79]
### Description

Switching from ListView to CardView is somewhat hidden in the settings page.
It may be good to switch to something like [this](https://github.com/gjiazhe/LayoutSwitch).

**Comment by anandkumarkparmar** [comment]
Hi @aminecmi, I would love to contribute in this project. Can I work on this?

**Comment by anandkumarkparmar** [comment]
Thanks @aminecmi.

**Comment by anandkumarkparmar** [comment]
Hi @aminecmi, Can you please help me to setup the project? I have imported the project in Android Studio. I have to set 3 parameters in gradle.properties .

What will be the value of those params? In the starting of the app I have to enter some url, what is that url?

**Comment by aminecmi** [comment]
As mentionned [here](https://github.com/aminecmi/ReaderforSelfoss/blob/master/.github/CONTRIBUTING.md), the gradle properties are not mandatory. They are only used when testing.

If you want to use the app, you have to use your [selfoss](https://selfoss.aditu.de/) instance, or install one. If you want help installing selfoss, you could ask for help on the [github page](https://github.com/SSilence/selfoss) of the project.

**Comment by aminecmi** [comment]
@anandkumarkparmar are you still working on the issue ?

**Comment by aminecmi** [comment]
@anandkumarkparmar I removed the `Taken` status.
