### ISSUE TITLE
Use the kotlin coding style

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#99]
[Style guide](https://android.github.io/kotlin-guides/style.html)

**Comment by shubham-negi** [comment]
Hi I would like to contribute, if you accept this could be the very first open-source contribution. It would be great if you could just tell me in details what needs to be done.

**Comment by aminecmi** [comment]
Hi @shubham-negi , this issue would be a great first contribution !

All you'll have to do is use the [kotlin style guide](https://android.github.io/kotlin-guides/style.html) to format the kotlin code of the app.

It should be easy, even if you don't know a lot about kotlin.

**Comment by shubham-negi** [comment]
Wooo @aminecmi , you're real quick watching over the issue ;D . Great
I've started looking into the style guide, in the meantime how do I start working. (newbie questions ;p)

**Comment by aminecmi** [comment]
The [contribution guide](https://github.com/aminecmi/ReaderforSelfoss/blob/master/.github/CONTRIBUTING.md) should help you set up the project and get started.

**Comment by shubham-negi** [comment]
@aminecmi I've gone through the instruction and ready to start. I'll just configure the development environment and will get back to you if stuck somewhere.

**Comment by shubham-negi** [comment]
@aminecmi I need a bit of your time to configure and run project.

**Comment by aminecmi** [comment]
@shubham-negi what's the problem ? Do you have a specific error ?

**Comment by shubham-negi** [comment]
I'll downloaded installed the latest community IntelliJ, but following the steps mentioned I'm lost. Can you help me into that.

**Comment by aminecmi** [comment]
Let's talk about this on the gitter chat please. I mentioned you, if you didn't receive any notification, the link is in the readme.

**Comment by aminecmi** [comment]
I cleaned the comments because they weren't related to the issue itself ?
